//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitRobots.TradeScriptConverter.Generators.MQL5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfitRobots.TradeScriptConverter.Generators.MQL5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #property strict
        ///
        ///&lt;&lt;INDICATOR_TYPE&gt;&gt;
        ///&lt;&lt;INDICATOR_BUFFERS&gt;&gt;
        ///&lt;&lt;INDICATOR_PLOTS&gt;&gt;
        ///&lt;&lt;HLINES&gt;&gt;
        ///
        ///&lt;&lt;INPUT_PARAMETERS&gt;&gt;
        ///input int bars_limit = 1000; // Bars limit
        ///&lt;&lt;INDICATOR_BUFFERS_DEFINITION&gt;&gt;
        ///&lt;&lt;VARIABLES_DEFINITION&gt;&gt;
        ///
        ///string IndicatorObjPrefix;
        ///
        ///bool NamesCollision(const string name)
        ///{
        ///   for (int k = ObjectsTotal(0); k &gt;= 0; k--)
        ///   {
        ///      if (StringFind(ObjectName(0, k), name) == 0)
        ///      {
        ///         return true;
        ///      }
        ///   }
        ///   return false;
        ///}
        ///
        ///string GenerateIndicatorPrefix(const s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indicator_base_mq5 {
            get {
                return ResourceManager.GetString("indicator_base.mq5", resourceCulture);
            }
        }
    }
}
